### PR TITLE
Catchup 8.0: eval.jax

### PR DESCRIPTION
**Pull request by k-takata**
Related: #27

まずは原文のマージと、一部の翻訳（主に自分が実装に関わった部分）を完了しました。
残りはのろのろ作業を進めていくつもりですが、やりたい方がいましたら、そのまま `catchup-8.0-eval` ブランチを進めていってもらってもかまいません。
おそらく関数単位で翻訳を進めるのがよいと思われます。

----

残件一覧

Chapter 1-3:

* [ ] non-zero-arg
* [ ] v:mouse_winid

Chapter 4:

* [ ] functions (関数リスト)
* [ ] assert_inrange
* [ ] assert_match
* [ ] assert_notequal
* [ ] assert_notmatch
* [ ] bufwinid
* [ ] ch_close
* [ ] ch_close_in
* [ ] ch_evalexpr
* [ ] ch_evalraw
* [ ] ch_getbufnr
* [ ] ch_getjob
* [ ] ch_info
* [ ] ch_log
* [ ] ch_logfile
* [ ] ch_open
* [ ] ch_read
* [ ] ch_readraw
* [ ] ch_sendexpr
* [ ] ch_sendraw
* [ ] ch_setoptions
* [ ] ch_status
* [ ] execute
* [ ] feedkeys
* [ ] funcref
* [ ] function
* [ ] garbagecollect
* [ ] get
* [ ] getbufinfo
* [ ] getbufvar
* [ ] getcompletion
* [ ] getloclist
* [ ] getqflist
* [ ] gettabinfo
* [ ] getwininfo
* [ ] glob2regpat
* [ ] job_getchannel
* [ ] job_info
* [ ] job_setoptions
* [ ] job_start
* [ ] job_status
* [ ] job_stop
* [ ] js_decode
* [ ] js_encode
* [ ] matchstrpos
* [ ] printf
* [ ] reltimefloat
* [ ] screenrow
* [ ] setfperm
* [ ] setloclist
* [ ] setqflist
* [ ] strcharpart
* [ ] strgetchar
* [ ] substitute
* [ ] test_alloc_fail
* [ ] test_autochdir
* [ ] test_disable_char_avail
* [ ] test_garbagecollect_now
* [ ] test_null_channel
* [ ] test_null_dict
* [ ] test_null_job
* [ ] test_null_list
* [ ] test_null_partial
* [ ] test_null_string
* [ ] test_settime
* [ ] timer_info
* [ ] timer_pause
* [ ] timer_start
* [ ] timer_stop
* [ ] timer_stopall
* [ ] win_findbuf
* [ ] win_getid
* [ ] win_gotoid
* [ ] win_id2tabwin
* [ ] win_id2win
* [ ] winwidth
* [ ] feature-list

Chapter 13:

* [ ] Testing

### CODE REVIEW

**Comment by k-takata** [comment]
差分がでかすぎてgithub上で見れない(´･ω･`)

**Comment by k-takata** [comment]
> 差分がでかすぎてgithub上で見れない(´･ω･`)

不便なので、今夜にでもパッチを分割して push -f する予定。

**Comment by k-takata** [comment]
done!

**Comment by k-takata** [comment]
残件一覧（ほぼ関数単位）を追加しました。

**Comment by koron** [comment]
翻訳の残作業は #48 でやるということでこちらはマージします。

**Pull request merged**
